spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/hyerintoy
  username: hyerintoy
  password: password

spring.jpa:
  hibernate.ddl-auto: create
  properties.hibernate.format_sql: true
  show-sql: true